apiVersion: v1
kind: Service
metadata:
  name: cabot-book-service
  namespace: cabot-book
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: web
      protocol: TCP
  selector:
    app: cabot-book

